server.port=5001
spring.application.name=auth-service

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/authdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
